export const SITE_CONFIG = {
    name: "Vitals Pathology & Diagnostic Lab",
    tagline: "Accurate Tests. Trusted Reports.",
    phone: "+91 98765 43210",
    email: "care@vitalslab.in",
    address: "Plot No. 12, Sector 5, Rohini, New Delhi - 110085",
    locations: ["Rohini", "Pitampura", "Dwarka", "Janakpuri", "Laxmi Nagar"],
    stats: [
        { label: "Tests Done", value: "100,000+" },
        { label: "Experience", value: "10+ Years" },
        { label: "Certified", value: "NABL/ISO" },
    ],
};

export const POPULAR_TESTS = [
    {
        id: "cbc",
        name: "Complete Blood Count (CBC)",
        price: 350,
        turnaroundTime: "12 Hours",
        description: "Evaluates overall health and detects specific disorders like anemia, infection, etc.",
        preparation: "No special preparation needed.",
        sampleType: "Blood",
    },
    {
        id: "hba1c",
        name: "HbA1c (Glycosylated Hemoglobin)",
        price: 500,
        turnaroundTime: "24 Hours",
        description: "Average blood sugar level over past 3 months.",
        preparation: "No fasting required.",
        sampleType: "Blood",
    },
    {
        id: "lft",
        name: "Liver Function Test (LFT)",
        price: 650,
        turnaroundTime: "24 Hours",
        description: "Check liver health and enzyme levels.",
        preparation: "10-12 hours fasting recommended.",
        sampleType: "Blood",
    },
    {
        id: "tft",
        name: "Thyroid Profile (T3, T4, TSH)",
        price: 550,
        turnaroundTime: "24 Hours",
        description: "Check thyroid function.",
        preparation: "Preferably empty stomach morning sample.",
        sampleType: "Blood",
    },
    {
        id: "kft",
        name: "Kidney Function Test (KFT)",
        price: 700,
        turnaroundTime: "24 Hours",
        description: "Check kidney health (Urea, Creatinine, etc).",
        preparation: "No special preparation needed.",
        sampleType: "Blood/Urine",
    },
];

export const HEALTH_PACKAGES = [
    {
        id: "basic-checkup",
        name: "Basic Health Checkup",
        price: 999,
        originalPrice: 1999,
        includes: ["CBC", "Blood Sugar Fasting", "Cholesterol Total", "Urine Routine"],
        turnaroundTime: "24 Hours",
        description: "Essential screening for general health.",
    },
    {
        id: "full-body",
        name: "Full Body Checkup",
        price: 1999,
        originalPrice: 4500,
        includes: ["CBC", "LFT", "KFT", "Lipid Profile", "Thyroid Profile", "Iron Studies", "Vitamin D", "Vitamin B12"],
        turnaroundTime: "48 Hours",
        description: "Comprehensive analysis of all vital organs.",
    },
    {
        id: "diabetes-care",
        name: "Diabetes Care Package",
        price: 1200,
        originalPrice: 2500,
        includes: ["HbA1c", "Blood Sugar (F/PP)", "Lipid Profile", "Creatinine"],
        turnaroundTime: "24 Hours",
        description: "Specialized package for diabetic patients.",
    },
];

export const ROUTINE_PATHOLOGY_TESTS = [
    {
        id: "dengue-ns1",
        name: "Dengue NS1 Antigen",
        price: 600,
        turnaroundTime: "24 Hours",
        description: "Early detection of Dengue virus.",
        preparation: "No special preparation needed.",
        sampleType: "Blood",
    },
    {
        id: "typhoid-widal",
        name: "Widal Test (Typhoid)",
        price: 300,
        turnaroundTime: "24 Hours",
        description: "Diagnosis of Typhoid fever.",
        preparation: "No special preparation needed.",
        sampleType: "Blood",
    },
    {
        id: "urine-routine",
        name: "Urine Routine & Microscopy",
        price: 200,
        turnaroundTime: "12 Hours",
        description: "Screening for UTI and kidney diseases.",
        preparation: "First morning mid-stream urine preferred.",
        sampleType: "Urine",
    },
    {
        id: "vitamin-d",
        name: "Vitamin D Total",
        price: 1200,
        turnaroundTime: "24 Hours",
        description: "Check Vitamin D levels for bone health.",
        preparation: "No special preparation needed.",
        sampleType: "Blood",
    },
    {
        id: "vitamin-b12",
        name: "Vitamin B12",
        price: 800,
        turnaroundTime: "24 Hours",
        description: "Check Vitamin B12 levels for nerve health.",
        preparation: "No special preparation needed.",
        sampleType: "Blood",
    },
    {
        id: "esr",
        name: "Erythrocyte Sedimentation Rate (ESR)",
        price: 150,
        turnaroundTime: "12 Hours",
        description: "Inflammation marker.",
        preparation: "No special preparation needed.",
        sampleType: "Blood",
    },
    {
        id: "blood-group",
        name: "Blood Group (ABO & Rh)",
        price: 200,
        turnaroundTime: "12 Hours",
        description: "Determine blood group.",
        preparation: "No special preparation needed.",
        sampleType: "Blood",
    },
    {
        id: "haemoglobin",
        name: "Haemoglobin (Hb)",
        price: 150,
        turnaroundTime: "6 Hours",
        description: "Check hemoglobin levels.",
        preparation: "No special preparation needed.",
        sampleType: "Blood",
    },
    {
        id: "bs-f-pp",
        name: "Blood Sugar (Fasting / PP)",
        price: 250,
        turnaroundTime: "12 Hours",
        description: "Diabetes monitoring.",
        preparation: "Fasting 10-12 hours / 2 hours post meal.",
        sampleType: "Blood",
    },
    {
        id: "lipid-profile",
        name: "Lipid Profile",
        price: 700,
        turnaroundTime: "24 Hours",
        description: "Cholesterol & Triglycerides check.",
        preparation: "12 hours fasting required.",
        sampleType: "Blood",
    },
    {
        id: "testosterone",
        name: "Testosterone Total",
        price: 900,
        turnaroundTime: "24 Hours",
        description: "Male hormone test.",
        preparation: "Morning sample preferred.",
        sampleType: "Blood",
    },
    {
        id: "malaria-antigen",
        name: "Malaria Antigen (Rapid)",
        price: 400,
        turnaroundTime: "4 Hours",
        description: "Rapid test for Malaria.",
        preparation: "No special preparation needed.",
        sampleType: "Blood",
    },
    {
        id: "urine-culture",
        name: "Urine Culture & Sensitivity",
        price: 800,
        turnaroundTime: "72 Hours",
        description: "Bacterial growth in urine.",
        preparation: "Sterile container mid-stream urine.",
        sampleType: "Urine",
    },
];
